### ISSUE TITLE
Invalid credentials raises exception

### ISSUE THREAD

**Issue by ckristhoff** [flavors/django-graphql-jwt#117] opened 2019-07-15 22:15 UTC
Hi,

Are invalid credentials supposed to raise an exception on the server? When I test tokenAuth mutation with wrong data Django server raises exception.

```
Traceback (most recent call last):
  File "/Users/cgf/.local/share/virtualenvs/testdjangoauthbackend-183R1gMP/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
    executor(resolve, reject)
  File "/Users/cgf/.local/share/virtualenvs/testdjangoauthbackend-183R1gMP/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
    return resolve(f(*args, **kwargs))
  File "/Users/cgf/.local/share/virtualenvs/testdjangoauthbackend-183R1gMP/lib/python3.7/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/Users/cgf/.local/share/virtualenvs/testdjangoauthbackend-183R1gMP/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 106, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/Users/cgf/.local/share/virtualenvs/testdjangoauthbackend-183R1gMP/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 89, in wrapper
    _('Please, enter valid credentials'))
graphql.error.located_error.GraphQLLocatedError: Please, enter valid credentials
```

I only was following the tutorial on documentation.

**Comment by Fel-o** [comment] 2019-07-27 10:21
Yes, this is intended behaviour. The exception is formatted by graphenes GraphQLView and can be found in the response to notify the client. The traceback is still printed though.
You can change this behaviour by catching JSONWebTokenError earlier:

```
class ObtainToken(ObtainJSONWebToken):
    @classmethod
    def mutate(cls, root, info, **kwargs):
        try:
            result = super().mutate(root, info, **kwargs)
        except JSONWebTokenError as e:
            return None
        else:
            return result
```

Or to post a custom error response create an ErrorType and attach it to the mutation:

```
class ObtainToken(ObtainJSONWebToken):
    errors = graphene.List(ErrorType, required=True)

    @classmethod
    def mutate(cls, root, info, **kwargs):
        try:
            result = super().mutate(root, info, **kwargs)
        except JSONWebTokenError as e:
            return ObtainToken(errors=[ErrorType(name=e.__name__, message="Invalid credentials!"])
        else:
            return result

    @classmethod
    def resolve(cls, root, info, **kwargs):
        return cls(errors=[])
```

**Comment by mongkok** [comment] 2019-10-19 20:37
Thank you for the clarification @Fel-o .

I close the issue, if you have any questions please let me know.

**Closed by mongkok** 2019-10-19 20:37 UTC
